---
title: "Data Summarizing"
author: "Allie Caughman"
date: "207-01-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Read in CSV

```{r}
output_df <- read_csv(here::here("03_generated_data", "model_outputs", "model40.csv"))

gc()
```

### Manipulate data

```{r}
# Summarize pop size and frequency by genotype
geno_sum2 <- output_df %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, genotype, rep) %>%
  summarise(geno_pop_sum = sum(pop, na.rm = TRUE))

pop_sum2 <- output_df %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop, na.rm = TRUE), 
            max_temp = max_temp, 
            min_temp = min_temp,
            fished_sum = sum(fished),
            pop_sd = sd(pop_sum, na.rm=TRUE)) %>% 
  ungroup() %>% 
  mutate(pop_se = pop_sd / sqrt(10)) %>% 
  mutate(pop_var = pop_sd^2)
```

```{r}
rm(output_df)

output_sum2 <- full_join(geno_sum2, pop_sum2) %>%
  mutate(freq = geno_pop_sum / pop_sum) %>% 
  distinct()

rm(pop_sum2, geno_sum2)

#write_csv(output_sum2, here::here("sensitivity_analysis", "replicate_check", "summary_m40_rep.csv"))

gc()

beepr::beep(5)
```

```{r}
data = output_sum2 %>% 
  filter(generation > 25) %>%
  mutate(generation = as.numeric(generation))

rm(output_sum2)

line_df <- data %>%
  group_by(generation, rep) %>%
  summarise(
    location_sum = sum(geno_pop_sum, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>% 
  mutate(rep = as.factor(rep))
```

```{r}
p = ggplot(line_df, aes(generation, location_sum)) +
  geom_line(aes(color = rep)) +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Replicate"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(panel.grid.minor = element_blank()) +
  scale_color_viridis_d()

ggsave(p, file = paste0("m40.pdf"), path = here::here("sensitivity_analysis", "replicate_check"), height = 8, width = 7)

gc()
```

