---
title: "Figs"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(patchwork)
```

### Read in CSV

```{r}
df1 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_large_001.csv"))

df2 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_large_002.csv")) 

df3 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_large_003.csv"))

df4 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_large_004.csv")) %>%
  mutate(dd = 0.004)

df5 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_large_005.csv")) %>%
  mutate(dd = 0.005)
```

### Manipulate data

##### 1

```{r}
# Summarize pop size and frequency by genotype
geno_sum1 <- df1 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean1 <- geno_sum1 %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm = TRUE))

pop_sum1 <- df1 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean1 <- pop_sum1 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum1 <- full_join(geno_mean1, pop_mean1) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum1 <- output_sum1 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df1 <- output_sum1 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)



rm(df1)
rm(geno_sum1)
rm(pop_sum1)
```

##### 2

```{r}
# Summarize pop size and frequency by genotype
geno_sum2 <- df2 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean2 <- geno_sum2 %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm = TRUE))

pop_sum2 <- df2 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean2 <- pop_sum2 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum2 <- full_join(geno_mean2, pop_mean2) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum2 <- output_sum2 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df2 <- output_sum2 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)



rm(df2)
rm(geno_sum2)
rm(pop_sum2)
```

##### 3

```{r}
# Summarize pop size and frequency by genotype
geno_sum3 <- df3 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean3 <- geno_sum3 %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm = TRUE))

pop_sum3 <- df3 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean3 <- pop_sum3 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum3 <- full_join(geno_mean3, pop_mean3) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum3 <- output_sum3 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df3 <- output_sum3 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change


rm(df3)
rm(geno_sum3)
rm(pop_sum3)
```

##### 4

```{r}
# Summarize pop size and frequency by genotype
geno_sum4 <- df4 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean4 <- geno_sum4 %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm = TRUE))

pop_sum4 <- df4 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean4 <- pop_sum4 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum4 <- full_join(geno_mean4, pop_mean4) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum4 <- output_sum4 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df4 <- output_sum4 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)



rm(df4)
rm(geno_sum4)
rm(pop_sum4)
```

##### 5

```{r}
# Summarize pop size and frequency by genotype
geno_sum5 <- df5 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean5 <- geno_sum5 %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm = TRUE))

pop_sum5 <- df5 %>%
  filter(age == "adult") %>%
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean5 <- pop_sum5 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum5 <- full_join(geno_mean5, pop_mean5) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum5 <- output_sum5 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df5 <- output_sum5 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

rm(df5)
rm(geno_sum5)
rm(pop_sum5)
```


```{r}
### SMALL
# lon %in% c(9, 10, 11)
# lat %in% c(49, 50, 51)

### MED
# lon %in% c(8, 9, 10, 11, 12, 13)
# lat %in% c(48, 49, 50, 51, 52, 53)

### LARGE
# lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)
# lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)

## SELECT ADULTS ONLY <-edit to change
mpa_df1 <- output_sum1 %>%
  filter(lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)) %>%
  filter(lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  mutate(dd = 0.001)

## SELECT ADULTS ONLY <-edit to change
mpa_df2 <- output_sum2 %>%
  filter(lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)) %>%
  filter(lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  mutate(dd = 0.002)

mpa_df3 <- output_sum3 %>%
  filter(lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)) %>%
  filter(lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  mutate(dd = 0.003)

## SELECT ADULTS ONLY <-edit to change
mpa_df4 <- output_sum4 %>%
  filter(lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)) %>%
  filter(lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  mutate(dd = 0.004)

## SELECT ADULTS ONLY <-edit to change
mpa_df5 <- output_sum5 %>%
  filter(lon %in% c(4,5,6,7,8, 9, 10, 11, 12, 13, 14,15)) %>%
  filter(lat %in% c(45,46,47,48, 49, 50, 51, 52, 53,54,55,56)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  mutate(dd = 0.005)
```


```{r}
data <- full_join(mpa_df1, mpa_df2)
data <- full_join(data, mpa_df3)
data <- full_join(data, mpa_df4)
data <- full_join(data, mpa_df5 ) %>%
  mutate(dd = as.factor(dd))


write_csv(data, here::here("sensitivity_analysis", "density_dependence", "null_large_sum.csv"))
```

