---
title: "Data Processing"
author: "Allie Caughman"
date: "2023-01-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Read in CSV

```{r}
df11_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m11_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df12_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m12_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df13_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m13_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df14_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m14_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df15_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m15_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df16_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m16_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(climate_rate = 0.013)

df19_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m19_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)
df20_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m20_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)
df21_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m21_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)
df22_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m22_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)
df23_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m23_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)
df24_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m24_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(climate_rate = 0.013)

df35_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m35_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df36_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m36_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df37_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m37_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df38_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m38_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df39_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m39_2.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
df40_2 = read_csv(here::here("03_generated_data", "summary_data", "summary_m40_2.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(climate_rate = 0.013)
```

```{r}
df_list2 = list(df11_2, df12_2, df13_2, df14_2, df15_2, df16_2, df19_2, df20_2, 
               df21_2) %>% 
  reduce(full_join)

rm(df11_2, df12_2, df13_2, df14_2, df15_2, df16_2, df19_2, df20_2, 
               df21_2) 
               
df_list3 = list(df22_2, df23_2, df24_2, df35_2, df36_2, df37_2, df38_2, df39_2, df40_2) %>% 
  reduce(full_join)

rm(df22_2, df23_2, df24_2, df35_2, df36_2, df37_2, df38_2, df39_2, df40_2)

df_list2 = rbind(df_list2, df_list3)

rm(df_list3)
```

```{r}
df_list = read_csv(here::here("03_generated_data", "summary_data", "full_sum.csv")) %>%
  filter(climate %in% c("Mean Shift", "El Nino/La Nina", "Shocks with Mean Shift")) %>% 
  mutate(climate_rate = 0.033)
```

```{r}
dfs = rbind(df_list, df_list2)

rm(df_list, df_list2)

write_csv(df_list, here::here("03_generated_data", "summary_data", "full_sum_climate_rate.csv"))
```

