---
title: "Data Processing"
author: "Allie Caughman"
date: "2023-01-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Read in CSV

```{r}
df11 = read_csv(here::here("03_generated_data", "summary_data", "summary_m11_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df13 = read_csv(here::here("03_generated_data", "summary_data", "summary_m13_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df15 = read_csv(here::here("03_generated_data", "summary_data", "summary_m15_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df12 = read_csv(here::here("03_generated_data", "summary_data", "summary_m12_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df14 = read_csv(here::here("03_generated_data", "summary_data", "summary_m14_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df16 = read_csv(here::here("03_generated_data", "summary_data", "summary_m16_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)

df19 = read_csv(here::here("03_generated_data", "summary_data", "summary_m19_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df21 = read_csv(here::here("03_generated_data", "summary_data", "summary_m21_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df23 = read_csv(here::here("03_generated_data", "summary_data", "summary_m23_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df20 = read_csv(here::here("03_generated_data", "summary_data", "summary_m20_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df22 = read_csv(here::here("03_generated_data", "summary_data", "summary_m22_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df24 = read_csv(here::here("03_generated_data", "summary_data", "summary_m24_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)

df35 = read_csv(here::here("03_generated_data", "summary_data", "summary_m35_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df37 = read_csv(here::here("03_generated_data", "summary_data", "summary_m37_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df39 = read_csv(here::here("03_generated_data", "summary_data", "summary_m39_3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df36 = read_csv(here::here("03_generated_data", "summary_data", "summary_m36_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df38 = read_csv(here::here("03_generated_data", "summary_data", "summary_m38_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df40 = read_csv(here::here("03_generated_data", "summary_data", "summary_m40_3.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)

df_list2 = list(df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24, df35, df36, df37, df38, df39, df40) %>% 
  reduce(full_join)

write_csv(df_list2, here::here("sum_fishing_pressure.csv"))

rm(df3, df4, df5, df6, df7, df8,  
               df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24, df27, df28, df29, df30, 
     df31, df32, df35, df36, df37, df38, df39, df40)
```

```{r}
df11 = read_csv(here::here("03_generated_data", "summary_data", "summary_m11.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df13 = read_csv(here::here("03_generated_data", "summary_data", "summary_m13.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df15 = read_csv(here::here("03_generated_data", "summary_data", "summary_m15.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df12 = read_csv(here::here("03_generated_data", "summary_data", "summary_m12.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df14 = read_csv(here::here("03_generated_data", "summary_data", "summary_m14.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df16 = read_csv(here::here("03_generated_data", "summary_data", "summary_m16.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)

df19 = read_csv(here::here("03_generated_data", "summary_data", "summary_m19.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df21 = read_csv(here::here("03_generated_data", "summary_data", "summary_m21.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df23 = read_csv(here::here("03_generated_data", "summary_data", "summary_m23.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df20 = read_csv(here::here("03_generated_data", "summary_data", "summary_m20.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df22 = read_csv(here::here("03_generated_data", "summary_data", "summary_m22.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)
df24 = read_csv(here::here("03_generated_data", "summary_data", "summary_m24.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina") %>% 
  mutate(fishing_pressure = 0.3)

df35 = read_csv(here::here("03_generated_data", "summary_data", "summary_m35.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df37 = read_csv(here::here("03_generated_data", "summary_data", "summary_m37.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df39 = read_csv(here::here("03_generated_data", "summary_data", "summary_m39.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df36 = read_csv(here::here("03_generated_data", "summary_data", "summary_m36.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df38 = read_csv(here::here("03_generated_data", "summary_data", "summary_m38.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)
df40 = read_csv(here::here("03_generated_data", "summary_data", "summary_m40.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift") %>% 
  mutate(fishing_pressure = 0.3)

df_list = list(df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24, df35, df36, df37, df38, df39, df40) %>% 
  reduce(full_join)

rm(df3, df4, df5, df6, df7, df8,  
               df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24, df27, df28, df29, df30, 
     df31, df32, df35, df36, df37, df38, df39, df40)
```


```{r}
dfs = rbind(df_list, df_list2)

rm(df_list, df_list2)

write_csv(dfs, here::here("03_generated_data", "summary_data", "full_sum_fishing_pressure.csv"))
```

