---
title: "Data Processing"
author: "Allie Caughman"
date: "2023-01-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Read in CSV

```{r}
df3 = read_csv(here::here("03_generated_data", "summary_data", "summary_m3.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Null")
df4 = read_csv(here::here("03_generated_data", "summary_data", "summary_m4.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Null")
df5 = read_csv(here::here("03_generated_data", "summary_data", "summary_m5.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Null")
df6 = read_csv(here::here("03_generated_data", "summary_data", "summary_m6.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Null")
df7 = read_csv(here::here("03_generated_data", "summary_data", "summary_m7.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Null")
df8 = read_csv(here::here("03_generated_data", "summary_data", "summary_m8.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Null")

df11 = read_csv(here::here("03_generated_data", "summary_data", "summary_m11.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift")
df12 = read_csv(here::here("03_generated_data", "summary_data", "summary_m12.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Mean Shift")
df13 = read_csv(here::here("03_generated_data", "summary_data", "summary_m13.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift")
df14 = read_csv(here::here("03_generated_data", "summary_data", "summary_m14.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Mean Shift")
df15 = read_csv(here::here("03_generated_data", "summary_data", "summary_m15.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift")
df16 = read_csv(here::here("03_generated_data", "summary_data", "summary_m16.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Mean Shift")

df19 = read_csv(here::here("03_generated_data", "summary_data", "summary_m19.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina")
df20 = read_csv(here::here("03_generated_data", "summary_data", "summary_m20.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "El Nino/La Nina")
df21 = read_csv(here::here("03_generated_data", "summary_data", "summary_m21.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina")
df22 = read_csv(here::here("03_generated_data", "summary_data", "summary_m22.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "El Nino/La Nina")
df23 = read_csv(here::here("03_generated_data", "summary_data", "summary_m23.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina")
df24 = read_csv(here::here("03_generated_data", "summary_data", "summary_m24.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "El Nino/La Nina")

df27 = read_csv(here::here("03_generated_data", "summary_data", "summary_m27.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks")
df28 = read_csv(here::here("03_generated_data", "summary_data", "summary_m28.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks")
df29 = read_csv(here::here("03_generated_data", "summary_data", "summary_m29.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks")
df30 = read_csv(here::here("03_generated_data", "summary_data", "summary_m30.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks")
df31 = read_csv(here::here("03_generated_data", "summary_data", "summary_m31.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks")
df32 = read_csv(here::here("03_generated_data", "summary_data", "summary_m32.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks")

df35 = read_csv(here::here("03_generated_data", "summary_data", "summary_m35.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift")
df36 = read_csv(here::here("03_generated_data", "summary_data", "summary_m36.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Small") %>% 
  mutate(climate = "Shocks with Mean Shift")
df37 = read_csv(here::here("03_generated_data", "summary_data", "summary_m37.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift")
df38 = read_csv(here::here("03_generated_data", "summary_data", "summary_m38.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Medium") %>% 
  mutate(climate = "Shocks with Mean Shift")
df39 = read_csv(here::here("03_generated_data", "summary_data", "summary_m39.csv")) %>%
  mutate(evolution = "Yes") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift")
df40 = read_csv(here::here("03_generated_data", "summary_data", "summary_m40.csv")) %>%
  mutate(evolution = "No") %>% 
  mutate(mpa_size = "Large") %>% 
  mutate(climate = "Shocks with Mean Shift")

beepr::beep(5)
```

```{r}
df_list = list(df3, df4, df5, df6, df7, df8,  
               df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24) %>% 
  reduce(full_join)

rm(df3, df4, df5, df6, df7, df8,  
               df11, df12, df13, df14, df15, df16, df19, df20, 
               df21, df22, df23, df24)

df_list2 = list(df27, df28, df29, df30, 
     df31, df32, df35, df36, df37, df38, df39, df40) %>% 
  reduce(full_join)

rm(df27, df28, df29, df30, 
     df31, df32, df35, df36, df37, df38, df39, df40)

dfs = full_join(df_list, df_list2)

rm(df_list, df_list2)

write_csv(dfs, here::here("03_generated_data", "summary_data", "full_sum.csv"))
```

