---
title: "Stats Tests"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(effsize)
library(effectsize)
```

### Load in Data

```{r}
# read in data

m1 <- read_csv(here::here("03_generated_data", "model_outputs", "model1.csv")) %>%
  filter(generation > 25) %>%
  group_by(lat, lon, generation) %>%
  summarise(geno_pop_sum = sum(pop)) %>%
  mutate(type = "null small")

# merge data

data <- m1

rm(m1)
```

### manipulate data

```{r}
sum <- data %>%
  group_by(type, generation) %>%
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))

# write_csv(sum_climate, here::here("03_generated_data", "summary_data", "test_null_sum.csv"))

data_f <- data %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) 

sum_f <- data_f %>%
  group_by(type, generation) %>%
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))

# write_csv(sum_f, here::here("03_generated_data", "summary_data", "test_null_sum_mpa.csv"))
```

### Repeated measures ANOVA

```{r}
anova_mod <- aov(formula = geno_pop_sum ~ type + Error(location / type), data = data_f)

eta_squared(anova_mod, partial = TRUE)
eta_squared(anova_mod, partial = FALSE)

pairwise.t.test(
  x = data_f$geno_pop_sum,
  g = data_f$type,
  p.adjust.method = "bonferroni"
)
```
