---
title: "Figs"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(patchwork)
```

### Read in Data

```{r}
data <- read_csv(here::here("03_generated_data", "summary_data", "full_sum.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  filter(mpa_size != "None") %>%
  mutate(climate = fct_relevel(climate, c("Null", "Shocks", "Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina")))
```

### Data Manipulation

```{r}
line_df_mpa_full <- data %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "Small") | (lat %in% c(47:52) & mpa_size == "Medium") | (lat %in% c(46:55) & mpa_size == "Large")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "Small") | (lon %in% c(9:14) & mpa_size == "Medium") | (lon %in% c(5:14) & mpa_size == "Large")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_geno_lat <- data %>%
  group_by(generation, evolution, mpa_size, climate, genotype, lat) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_df_geno_lat = line_df_geno_lat %>%
  filter(lat == 10 | lat == 90 | lat == 50)

line_lat_mpa_combo = line_df_geno_lat %>% 
  filter(lat != 50) %>% 
  group_by(generation, climate, genotype, lat) %>% 
  summarize(mpa_mean_freq = mean(freq_avg, na.rm = TRUE)) %>% 
  mutate(location = case_when(
    lat == 10 ~ "Low Latitude", 
    lat == 90 ~ "High Latitude"
  )) %>% 
  mutate(mpa_size = "Non-MPA")

geno_lat = line_df_geno_lat %>% 
  filter(lat == 50) %>% 
  mutate(location = "MPA") %>% 
  mutate(mpa_mean_freq = freq_avg) %>% 
  full_join(line_lat_mpa_combo) %>% 
  mutate(location = as.factor(location)) %>% 
  mutate(mpa_size = as.factor(mpa_size)) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("Large", "Medium", "Small", "Non-MPA")))

mpa_medium = line_df_mpa_full %>% 
  filter(mpa_size == "Medium")

collapse_full = line_df_mpa_full %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "Small") | (location_sum <= (100*2*.05*6*6) & mpa_size == "Medium") | (location_sum <= (100*2*.05*10*10) & mpa_size == "Large")) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "Small" ~ 100*2*.05*3*3,
    mpa_size == "Medium" ~ 100*2*.05*6*6,
    mpa_size == "Large" ~ 100*2*.05*10*10
  ))
```

### Paper Figures

```{r}
f2 = ggplot(mpa_medium, aes(generation, location_sum)) +
  geom_line(aes(linetype = evolution)) +
  theme_bw(base_size = 12) +
  facet_wrap(~ climate, ncol = 1) +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Scenario", 
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154")) 
  
ggsave(f2, file = paste0("decline_mpa.pdf"), path = here::here("04_figs"), height = 10, width = 12)
```

```{r}
f3 = ggplot(collapse_full, aes(min_gen, mpa_size)) +
  geom_point(aes(color = climate, shape = evolution), size = 3) +
  theme_bw(base_size = 12) +
  scale_color_manual(values = c("#5ec962", "#fde725", "#3b528b", "#440154")) +
  labs(
    x = "Year",
    y = "MPA Size",
    color = "Climate Scenario",
    shape = "Evolution?"
  ) + 
  theme(panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(f3, file = paste0("collapse_points.pdf"), path = here::here("04_figs"), height = 8, width = 10)
```

```{r}
f4 = ggplot(geno_lat, aes(generation, mpa_mean_freq)) +
  geom_line(aes(color = location, linetype = mpa_size)) +
  facet_grid(genotype~climate, scales = "free_y") +
  theme_bw(base_size = 12) +
  labs(
    x = "Year",
    y = "Allele Frequency",
    color = "Location",
    linetype = "MPA Size"
  ) +
  theme() +
  scale_color_viridis_d() +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted", "solid"), labels = c("Large", "Medium", "Small", ""))

ggsave(f4, file = paste0("genotype_summary.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

### Presentation Figs

```{r}
mpa_medium_pres = mpa_medium %>% 
  filter(climate %in% c("Null", "Mean Shift")) %>% 
  mutate(climate = case_when(
    climate == "Null" ~ "No Climate Change",
    climate == "Mean Shift" ~ "Mean Change Per Year"
  ))

p1 = ggplot(mpa_medium_pres, aes(generation, location_sum)) +
  geom_line(aes(color = climate, linetype = evolution), linewidth = 2) +
  theme_bw(base_size = 20) +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Scenario", 
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#5ec962", "#440154")) +
  scale_linetype_manual(values = c("solid", "dashed"))
  
ggsave(p1, file = paste0("decline_mpa_pres.pdf"), path = here::here("04_figs", "presentation"), height = 10, width = 18)
```

```{r}
geno_lat_pres = geno_lat %>% 
  filter(location == "MPA") %>% 
  filter(climate %in% c("Null", "Mean Shift")) %>% 
  mutate(climate = case_when(
    climate == "Null" ~ "No Climate Change",
    climate == "Mean Shift" ~ "Mean Change Per Year"
  )) %>% 
  filter(mpa_size == "Medium")

p2 = ggplot(geno_lat_pres, aes(generation, mpa_mean_freq)) +
  geom_line(aes(color = mpa_size), linewidth = 2) +
  facet_grid(genotype~climate, scales = "free_y") +
  theme_bw(base_size = 20) +
  labs(
    x = "Year",
    y = "Allele Frequency",
    color = "MPA Size"
  ) +
  theme() +
  scale_color_viridis_d() +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(p2, file = paste0("genotype_summary_pres.pdf"), path = here::here("04_figs", "presentation"), height = 8, width = 15)
```

