---
title: "Stats Tests"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Data 

### Load in Data

```{r}
# read in data
data <- read_csv(here::here("03_generated_data", "summary_data", "full_sum.csv")) %>% 
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Null", "Shocks", "Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("1 x 1", "3 x 3", "6 x 6", "10 x 10")))
```

### Manipulate Data

```{r}
line_df <- data %>%
  filter(generation > 25) %>%
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)

line_df_mpa_full <- data %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)

line_df_geno <- data %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  group_by(generation, evolution, mpa_size, climate, genotype) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes")

line_df_geno_lat <- data %>%
  group_by(generation, evolution, mpa_size, climate, genotype, lat) %>%
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_df_lat <- data %>%
  filter(generation > 25) %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  group_by(generation, mpa_size, climate, lat, lon, evolution) %>%
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))
```

# Population Density

### Population Max

```{r}
pop_max = line_df_mpa_full %>% 
  group_by(evolution, mpa_size, climate) %>% 
  summarize(max_pop = max(location_sum))

write_csv(pop_max, here::here("03_generated_data", "results", "pop_max.csv"))
```

### Evo No Evo Compare

```{r}
point_n = line_df_lat %>% 
  filter(evolution == "No") %>%
  rename(no = location_sum) %>% 
  select(-freq_avg, -evolution, -max_temp, -min_temp)
point_y = line_df_lat %>% 
  filter(evolution == "Yes") %>% 
  rename(yes = location_sum) %>% 
  select(-freq_avg, -evolution, -max_temp, -min_temp)
point = full_join(point_y, point_n) %>% 
  mutate(diff = yes - no) 

point1 = point %>% 
  filter(generation == 50) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 50)

point2 = point %>% 
  filter(generation == 75) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 75)

point3 = point %>% 
  filter(generation == 100) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 100)

point4 = point %>% 
  filter(generation == 125) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 125)

point5 = point %>% 
  filter(generation == 150) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 150)

point6 = point %>% 
  filter(generation == 175) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 175)

point_sum = list(point1, point2, point3, point4, point5, point6) %>% 
  reduce(full_join) %>% 
  filter(mpa_size == "6 x 6")

write_csv(point, here::here("03_generated_data", "results", "evo_diff.csv"))
write_csv(point_sum, here::here("03_generated_data", "results", "evo_diff_sum.csv"))
```


### Collapse Point

```{r}
collapse_full = line_df %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter(location_sum <= 100*2*.05*100*20) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = 100*2*.05*100*20) %>% 
  mutate(area = "full sim")

collapse_mpa = line_df_mpa_full %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10") | (location_sum <= (100*2*.05) & mpa_size == "1 x 1")) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "1 x 1" ~ 100*2*0.05,
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  )) %>% 
  mutate(area = "mpa only")

collapse = full_join(collapse_full, collapse_mpa) 

write_csv(collapse, here::here("03_generated_data", "results", "collapse_points.csv"))
```

### Derivative

```{r}
change = data %>% 
  select(-genotype, -geno_pop_mean, -freq, -fished_mean, -geno_pop_sd, -geno_pop_se) %>% 
  distinct() %>% 
  group_by(climate, evolution, mpa_size) %>% 
  mutate(rate = pop_mean - lag(pop_mean, default = first(pop_mean), order_by = generation)) %>% 
  ungroup()

change_mpa = change %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1"))

mean_change_mpa = change_mpa %>% 
  group_by(generation, climate, evolution, mpa_size) %>% 
  summarize(mean_change = mean(rate2, na.rm = TRUE))

write_csv(mean_change_mpa, here::here("03_generated_data", "results", "rate_change_mpa.csv"))
```

### Heatwave Recovery

```{r}
shock_df = line_df %>% 
  filter(climate %in% c("Shocks")) %>% 
  ungroup() %>% 
  select(generation, climate, max_temp, mpa_size, evolution) %>% 
  distinct() %>% 
  filter(max_temp > 27)

shock_years = shock_df %>% 
  filter(mpa_size == "3 x 3") %>% 
  mutate(shock_year = "Yes") %>% 
  select(generation, shock_year)

shock_change = mean_change_mpa %>% 
  filter(climate == "Shocks")

shock_change = list(shock_change, shock_years) %>% 
  reduce(left_join)

years = shock_years %>% 
  select(generation)

ggplot(shock_change, aes(generation, mean_change)) +
  geom_vline(data = years, aes(xintercept = generation), alpha = 0.3, linetype = "dotted") + 
  geom_line(aes(linetype = evolution)) +
  facet_wrap(~ mpa_size, scales = "free_y") +
  theme_bw()

write_csv(shock_change, here::here("03_generated_data", "results", "shock_change.csv"))
```

### Temp of max aa

```{r}
aa_geno = line_df_geno %>% 
  filter(genotype == "aa") %>%
  filter(climate %in% c("Mean Shift", "Shocks with Mean Shift", "El Nino/La Nina")) %>% 
  filter(!is.na(freq_avg)) %>% 
  select(-evolution, -genotype) %>% 
  mutate(average_survival = sum(max_survival, min_survival)/2,
         average_temp = sum(max_temp, min_temp)/2)

aa_sum = aa_geno %>% 
  group_by(mpa_size, climate) %>% 
  summarize(freq_avg = max(freq_avg))

aa = left_join(aa_sum, aa_geno)

temps = aa %>% 
  select(mpa_size, climate, freq_avg, average_temp, generation)

write_csv(temps, here::here("03_generated_data", "results", "aa_peak.csv"))
```

### Temp aa decline

```{r}
aa_geno_rate = aa_geno %>% 
  select(evolution, generation, mpa_size, climate, freq_avg, average_temp, average_survival) %>% 
  distinct() %>% 
  group_by(climate, evolution, mpa_size) %>% 
  mutate(rate = freq_avg - lag(freq_avg, default = first(freq_avg), order_by = generation)) %>% 
  ungroup()

write_csv(aa_geno_rate, here::here("03_generated_data", "results", "aa_rate.csv"))
```


### Fishing Pressure

```{r}
data_fp <- read_csv(here::here("03_generated_data", "summary_data", "full_sum_fishing_pressure.csv")) %>%
  filter(generation <= 150) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  mutate(mpa_size = case_when(
    mpa_size == "Small" ~ "3 x 3",
    mpa_size == "Medium" ~ "6 x 6",
    mpa_size == "Large" ~ "10 x 10"
  ))
```

```{r}
line_df_mpa_full_fp <- data_fp %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate, fishing_pressure) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)

collapse_mpa_fp = line_df_mpa_full_fp %>% 
  select(generation, evolution, mpa_size, climate, location_sum, fishing_pressure) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10")) %>%  
  group_by(evolution, mpa_size, climate, fishing_pressure) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  )) %>%  
  mutate(area = "mpa only")

write_csv(collapse_mpa_fp, here::here("03_generated_data", "results", "collapse_fishing_pressure.csv"))

change_fp = data_fp %>% 
  select(-genotype, -geno_pop_mean, -freq, -fished_mean, -geno_pop_sd, -geno_pop_se) %>% 
  distinct() %>% 
  group_by(climate, evolution, mpa_size, fishing_pressure) %>% 
  mutate(rate = pop_mean - lag(pop_mean, default = first(pop_mean), order_by = generation)) %>% 
  ungroup()

change_mpa_fp = change_fp %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10"))

mean_change_mpa_fp = change_mpa_fp %>% 
  group_by(generation, climate, evolution, mpa_size) %>% 
  summarize(mean_change = mean(rate, na.rm = TRUE))

write_csv(mean_change_mpa_fp, here::here("03_generated_data", "results", "fishing_pressure_change_mpa.csv"))
```

### Climate Rate

```{r}
data_rate <- read_csv(here::here("03_generated_data", "summary_data", "full_sum_climate_rate.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  mutate(mpa_size = case_when(
    mpa_size == "Small" ~ "3 x 3",
    mpa_size == "Medium" ~ "6 x 6",
    mpa_size == "Large" ~ "10 x 10"
  ))
```

```{r}
line_df_mpa_full_rate <- data_rate %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate, climate_rate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)

collapse_mpa_rate = line_df_mpa_full_rate %>% 
  select(generation, evolution, mpa_size, climate, location_sum, climate_rate) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10")) %>% 
  group_by(evolution, mpa_size, climate, climate_rate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  )) %>% 
  mutate(area = "mpa only")

write_csv(collapse_mpa_rate, here::here("03_generated_data", "results", "collapse_climate_rate.csv"))

change_rate = data_rate %>% 
  select(-genotype, -geno_pop_mean, -freq, -fished_mean, -geno_pop_sd, -geno_pop_se) %>% 
  distinct() %>% 
  group_by(climate, evolution, mpa_size, climate_rate) %>% 
  mutate(rate = pop_mean - lag(pop_mean, default = first(pop_mean), order_by = generation)) %>% 
  ungroup()

change_mpa_rate = change_rate %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10"))

mean_change_mpa_rate = change_mpa_rate %>% 
  group_by(generation, climate, evolution, mpa_size) %>% 
  summarize(mean_change = mean(rate, na.rm = TRUE))

write_csv(mean_change_mpa_rate, here::here("03_generated_data", "results", "climate_rate_change_mpa.csv"))
```


# Old

### Repeated measures ANOVA

```{r}
anova_mod <- aov(formula = pop_mean ~ mpa_size*evolution*climate + Error(generation), data = data)

cohens_f_squared(anova_mod, partial = TRUE)
cohens_f_squared(anova_mod, partial = FALSE)

anova_mod_geno <- aov(formula = geno_pop_mean ~ mpa_size*evolution*climate + Error(generation), data = data)

cohens_f_squared(anova_mod_geno, partial = TRUE)
cohens_f_squared(anova_mod_geno, partial = FALSE)

anova_mod_sum <- aov(formula = pop_mean ~ mpa_size*evolution*climate + Error(generation), data = sum)

eta_squared(anova_mod_sum, partial = TRUE)
cohens_f_squared(anova_mod_sum, partial = TRUE)

#investigate options
```

### ANOVA At Points

```{r}
point1 = line_df_lat %>% 
  mutate(location = paste(as.character(lat), as.character(lon))) %>%
  filter(generation == 50)
anova_mod1 <- aov(formula = location_sum ~ mpa_size*evolution*climate + Error(location), data = point1)
TukeyHSD(anova_mod1, "evolution")

point2 = line_df_lat %>% 
  mutate(location = paste(as.character(lat), as.character(lon))) %>%
  filter(generation == 75)
anova_mod2 <- aov(formula = location_sum ~ mpa_size*evolution*climate + Error(location), data = point2)

point3 = line_df_lat %>% 
  mutate(location = paste(as.character(lat), as.character(lon))) %>%
  filter(generation == 100)
anova_mod3 <- aov(formula = location_sum ~ mpa_size*evolution*climate + Error(location), data = point3)

point4 = line_df_lat %>% 
  mutate(location = paste(as.character(lat), as.character(lon))) %>%
  filter(generation == 150)
anova_mod4 <- aov(formula = location_sum ~ mpa_size*evolution*climate + Error(location), data = point4)

```

### manipulate data

```{r}
sum <- data %>%
  group_by(generation, climate, evolution, mpa_size) %>%
  summarise(pop_mean = mean(pop_mean)) 

# write_csv(sum_climate, here::here("03_generated_data", "summary_data", "test_null_sum.csv"))
```

### Other

```{r}
large = line_df %>% 
  filter(mpa_size == "10 x 10") %>% 
  pull(location_sum)

medium = line_df %>% 
  filter(mpa_size == "6 x 6") %>% 
  pull(location_sum)

small = line_df %>% 
  filter(mpa_size == "3 x 3") %>% 
  pull(location_sum)

mean(large - small)
mean(large - medium)
mean(medium - small)
```