---
title: "Figs"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(patchwork)
```

### Read in CSV

```{r}
df1 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_001.csv"))

df2 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_002.csv"))

df3 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_003.csv"))

df4 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_004.csv"))

df5 <- read_csv(here::here("sensitivity_analysis", "density_dependence", "null_005.csv"))
```

### Manipulate data

##### 1

```{r}
# Summarize pop size and frequency by genotype
geno_sum1 <- df1 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean1 <- geno_sum1 %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm=TRUE))

pop_sum1 <- df1 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean1 <- pop_sum1 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum1 <- full_join(geno_mean1, pop_mean1) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum1 <- output_sum1 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df1 <- output_sum1 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change
mpa_df1 <- output_sum1 %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)
```

##### 2

```{r}
# Summarize pop size and frequency by genotype
geno_sum2 <- df2 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean2 <- geno_sum2 %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm=TRUE))

pop_sum2 <- df2 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean2 <- pop_sum2 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum2 <- full_join(geno_mean2, pop_mean2) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum2 <- output_sum2 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df2 <- output_sum2 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change
mpa_df2 <- output_sum2 %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)
```

##### 3

```{r}
# Summarize pop size and frequency by genotype
geno_sum3 <- df3 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean3 <- geno_sum3 %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm=TRUE))

pop_sum3 <- df3 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean3 <- pop_sum3 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum3 <- full_join(geno_mean3, pop_mean3) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum3 <- output_sum3 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df3 <- output_sum3 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change
mpa_df3 <- output_sum3 %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)
```

##### 4

```{r}
# Summarize pop size and frequency by genotype
geno_sum4 <- df4 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean4 <- geno_sum4 %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm=TRUE))

pop_sum4 <- df4 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean4 <- pop_sum4 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum4 <- full_join(geno_mean4, pop_mean4) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum4 <- output_sum4 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df4 <- output_sum4 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change
mpa_df4 <- output_sum4 %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)
```

##### 5

```{r}
# Summarize pop size and frequency by genotype
geno_sum5 <- df5 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(geno_pop_sum = sum(pop))

geno_mean5 <- geno_sum5 %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_mean = mean(geno_pop_sum, na.rm=TRUE))

pop_sum5 <- df5 %>%
  filter(age == "adult") %>% 
  group_by(lat, lon, generation, rep) %>%
  summarise(pop_sum = sum(pop), max_temp = max_temp, min_temp = min_temp)

pop_mean5 <- pop_sum5 %>%
  group_by(lat, lon, generation) %>%
  summarise(pop_mean = mean(pop_sum, rm.na = TRUE), max_temp = max_temp, min_temp = min_temp)

output_sum5 <- full_join(geno_mean5, pop_mean5) %>%
  mutate(freq = geno_pop_mean / pop_mean)

## SELECT GENERATIONS and ADULTS ONLY <-edit to change
plot_sum5 <- output_sum5 %>%
  filter(generation %in% c(25, 50, 75, 100, 125, 150, 175)) %>%
  mutate(generation = as.numeric(generation))

## SELECT ADULTS ONLY <-edit to change
line_df5 <- output_sum5 %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m) %>%
  filter(generation > 25)

## SELECT ADULTS ONLY <-edit to change
mpa_df5 <- output_sum5 %>%
  filter(lon %in% c(9, 10, 11)) %>%
  filter(lat %in% c(49, 50, 51)) %>%
  group_by(generation) %>%
  summarise(
    location_sum = sum(geno_pop_mean),
    max_temp = max(max_temp),
    min_temp = min(min_temp)
  ) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.59, 0.59, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.59, 0.59, max_m)) %>%
  select(-max_m, -min_m)

rm(df1)
rm(df2)
rm(df3)
rm(df4)
rm(df5)
rm(geno_sum1)
rm(geno_sum2)
rm(geno_sum3)
rm(geno_sum4)
rm(geno_sum5)
rm(pop_sum1)
rm(pop_sum2)
rm(pop_sum3)
rm(pop_sum4)
rm(pop_sum5)
```

### Line Plot Figures

```{r}
p1 <- ggplot(mpa_df1, aes(generation, location_sum)) +
  geom_line() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 16, alpha = 0.3) +
  geom_vline(xintercept = 26, alpha = 0.3) +
  # geom_vline(xintercept = c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129), alpha = 0.3, color= "red") +
  # scale_x_continuous(breaks = c(16, 26), labels = c("fishing starts", "MPA establishment")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p2 <- ggplot(mpa_df2, aes(generation, location_sum)) +
  geom_line() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 16, alpha = 0.3) +
  geom_vline(xintercept = 26, alpha = 0.3) +
  # geom_vline(xintercept = c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129), alpha = 0.3, color= "red") +
  # scale_x_continuous(breaks = c(16, 26), labels = c("fishing starts", "MPA establishment")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p3 <- ggplot(mpa_df3, aes(generation, location_sum)) +
  geom_line() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 16, alpha = 0.3) +
  geom_vline(xintercept = 26, alpha = 0.3) +
  # geom_vline(xintercept = c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129), alpha = 0.3, color= "red") +
  # scale_x_continuous(breaks = c(16, 26), labels = c("fishing starts", "MPA establishment")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p4 <- ggplot(mpa_df4, aes(generation, location_sum)) +
  geom_line() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 16, alpha = 0.3) +
  geom_vline(xintercept = 26, alpha = 0.3) +
  # geom_vline(xintercept = c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129), alpha = 0.3, color= "red") +
  # scale_x_continuous(breaks = c(16, 26), labels = c("fishing starts", "MPA establishment")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p5 <- ggplot(mpa_df5, aes(generation, location_sum)) +
  geom_line() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 16, alpha = 0.3) +
  geom_vline(xintercept = 26, alpha = 0.3) +
  # geom_vline(xintercept = c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129), alpha = 0.3, color= "red") +
  # scale_x_continuous(breaks = c(16, 26), labels = c("fishing starts", "MPA establishment")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

plot = p1 + p2 + p3 + p4 + p5 + plot_annotation(tag_levels = '1')

# mean 66, enso 117, shock c(136,66,124,79,35,143,130,71,82,90,25,73,80,103,51,34,142,40,86,141,97,137,113,144,122,132,149,129) EDIT WITH FINAL VALUES

ggsave(plot, file = paste0("null.pdf"), path = here::here("sensitivity_analysis", "density_dependence"), height = 8, width = 15)
```


```{r}
p4 <- ggplot(line_df, aes(generation, location_sum)) +
  geom_line() +
  facet_wrap(~genotype, nrow = 3, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Age"
  ) +
  geom_vline(xintercept = 73, alpha = 0.2) +
  scale_x_continuous(breaks = c(73), labels = c("Mortality < 0.2")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

p4
```
