---
title: "Figs"
author: "Allie Caughman"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(patchwork)
```

# Paper Figures 

### Read in Data

```{r}
data <- read_csv(here::here("generated_data", "summary_data", "full_sum.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Null", "Shocks", "Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("1 x 1", "3 x 3", "6 x 6", "10 x 10")))
```

### Data Manipulation

```{r}
line_df_mpa_full <- data %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_geno_lat <- data %>%
  group_by(generation, evolution, mpa_size, climate, genotype, lat) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_df_lat <- data %>%
  filter(generation > 25) %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lat %in% c(10) & mpa_size == "1 x 1")) %>% 
  group_by(generation, mpa_size, climate, lat, lon, evolution) %>%
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_df_geno_lat = line_df_geno_lat %>%
  filter(lat == 10 | lat == 90 | lat == 50)

line_lat_mpa_combo = line_df_geno_lat %>% 
  filter(lat != 50) %>% 
  group_by(generation, climate, genotype, lat) %>% 
  summarize(mpa_mean_freq = mean(freq_avg, na.rm = TRUE)) %>% 
  mutate(location = case_when(
    lat == 10 ~ "Low Latitude", 
    lat == 90 ~ "High Latitude"
  )) %>% 
  mutate(mpa_size = "Non-MPA")

geno_lat = line_df_geno_lat %>% 
  filter(lat == 50) %>% 
  mutate(location = "MPA") %>% 
  mutate(mpa_mean_freq = freq_avg) %>% 
  full_join(line_lat_mpa_combo) %>% 
  mutate(location = as.factor(location)) %>% 
  mutate(mpa_size = as.factor(mpa_size)) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("10 x 10", "6 x 6", "3 x 3", "Non-MPA")))

mpa_medium = line_df_mpa_full %>% 
  filter(mpa_size == "6 x 6")

collapse_full = line_df_mpa_full %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10") | (location_sum <= (100*2*.05) & mpa_size == "1 x 1")) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "1 x 1" ~ 100*2*.05,
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  )) %>% 
  filter(climate %in% c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))

point_n = line_df_lat %>% 
  filter(evolution == "No") %>%
  rename(no = location_sum) %>% 
  select(-freq_avg, -evolution, -max_temp, -min_temp)
point_y = line_df_lat %>% 
  filter(evolution == "Yes") %>% 
  rename(yes = location_sum) %>% 
  select(-freq_avg, -evolution, -max_temp, -min_temp)
point = full_join(point_y, point_n) %>% 
  mutate(diff = yes - no) 

point1 = point %>% 
  filter(generation == 50) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 50)

point2 = point %>% 
  filter(generation == 75) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 75)

point3 = point %>% 
  filter(generation == 100) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 100)

point4 = point %>% 
  filter(generation == 125) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 125)

point5 = point %>% 
  filter(generation == 150) %>% 
  group_by(mpa_size, climate) %>% 
  summarize(avg_diff = mean(diff, na.rm=TRUE)) %>% 
  mutate(generation = 150)

point_sum = list(point1, point2, point3, point4, point5) %>% 
  reduce(full_join) %>% 
  filter(mpa_size == "6 x 6")
```

### Paper Figures

```{r}
f2 = ggplot(mpa_medium, aes(generation, location_sum)) +
  geom_line(aes(linetype = evolution)) +
  theme_bw(base_size = 12) +
  facet_wrap(~ climate, ncol = 1) +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Scenario", 
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154")) 
  
ggsave(f2, file = paste0("fig2.pdf"), path = here::here("04_figs"), height = 10, width = 12)
```

```{r}
f3.1 = ggplot(collapse_full, aes(min_gen, mpa_size)) +
  geom_point(aes(color = climate, shape = evolution), size = 3) +
  theme_bw(base_size = 12) +
  scale_color_manual(values = c("#fde725", "#3b528b", "#440154")) +
  labs(
    x = "Year",
    y = "MPA Size",
    color = "Climate Scenario",
    shape = "Evolution?"
  ) + 
  theme(panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(f3.1, file = paste0("fig3.1.pdf"), path = here::here("04_figs"), height = 8, width = 10)
```

```{r}
f4 = ggplot(geno_lat, aes(generation, mpa_mean_freq)) +
  geom_line(aes(color = location, linetype = mpa_size)) +
  facet_grid(genotype~climate, scales = "free_y") +
  theme_bw(base_size = 12) +
  labs(
    x = "Year",
    y = "Allele Frequency",
    color = "Location",
    linetype = "MPA Size"
  ) +
  theme() +
  scale_color_viridis_d() +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted", "solid", "longdash"), labels = c("10 x 10", "6 x 6", "3 x 3", "1 x 1", ""))

ggsave(f4, file = paste0("fig4.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

```{r}
f3.2 = ggplot(point_sum, aes(generation, avg_diff)) +
  geom_line(aes(color = climate), linewidth = 1) +
  geom_point() +
  theme_bw() +
  labs(
    x = "Year",
    y = "Average Population Difference Between Evolution and No Evolution",
    color = "Climate Scenario") +
  scale_color_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154")) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted")) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

f3 = f3.2 + f3.1 + plot_annotation(tag_levels = "A") + plot_layout(guides = "collect")

ggsave(f3, file = paste0("fig3.pdf"), path = here::here("04_figs"), height = 8, width = 10)

ggsave(f3.2, file = paste0("fig3.2.pdf"), path = here::here("04_figs"), height = 8, width = 10)
```

# Supplemental Figures

## Main Figures

### Read in Data

```{r}
data <- read_csv(here::here("03_generated_data", "summary_data", "full_sum.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina")))  %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("1 x 1", "3 x 3", "6 x 6", "10 x 10")))
```

### Data Manipulation 

```{r}
line_df_mpa_full <- data %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df <- data %>%
  filter(generation > 25) %>%
  group_by(generation, evolution, mpa_size, climate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_mpa <- data %>%
  filter(generation > 25) %>%
  filter(lat == 50) %>% 
  filter((lon == 10)) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_geno <- data %>%
  group_by(generation, evolution, mpa_size, climate, genotype) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes")

line_df_geno_lat <- data %>%
  group_by(generation, evolution, mpa_size, climate, genotype, lat) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

change = data %>% 
  select(-genotype, -geno_pop_mean, -freq, -fished_mean, -geno_pop_sd, -geno_pop_se) %>% 
  distinct() %>% 
  group_by(climate, evolution, mpa_size, lat, lon) %>% 
  mutate(rate = pop_mean - lag(pop_mean, default = first(pop_mean), order_by = generation)) %>% 
  ungroup()
```

```{r}
mean_change2 = change %>% 
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(5:14) & mpa_size == "10 x 10") | (lon %in% c(10) & mpa_size == "1 x 1")) %>% 
  filter(generation >= 35) %>%
  group_by(generation, climate, evolution, mpa_size) %>%
  summarize(mean_change = mean(rate, na.rm = TRUE))

collapse_full = line_df_mpa_full %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10") | (location_sum <= (100*2*.05) & mpa_size == "1 x 1")) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "1 x 1" ~ 100*2*0.05,
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  ))

collapse = line_df %>% 
  select(generation, evolution, mpa_size, climate, location_sum) %>% 
  filter(generation > 30) %>% 
  filter(location_sum <= 100*2*.05*100*20) %>% 
  group_by(evolution, mpa_size, climate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = 100*2*.05*100*20)

line_df_geno_lat = line_df_geno_lat %>%
  filter(lat == 10 | lat == 90 | lat == 50)

line_lat_mpa_combo = line_df_geno_lat %>% 
  filter(lat != 50) %>% 
  group_by(generation, climate, genotype, lat) %>% 
  summarize(mpa_mean_freq = mean(freq_avg, na.rm = TRUE)) %>% 
  mutate(location = case_when(
    lat == 10 ~ "Low Latitude", 
    lat == 90 ~ "High Latitude"
  )) %>% 
  mutate(mpa_size = "Non-MPA")

geno_lat = line_df_geno_lat %>% 
  filter(lat == 50) %>% 
  mutate(location = "MPA") %>% 
  mutate(mpa_mean_freq = freq_avg) %>% 
  full_join(line_lat_mpa_combo) %>% 
  mutate(location = as.factor(location)) %>% 
  mutate(mpa_size = as.factor(mpa_size)) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("10 x 10", "6 x 6", "3 x 3", "Non-MPA")))
```

### Supplemental Figures

```{r}
s1 = ggplot(line_df, aes(generation, location_sum)) +
  geom_vline(data = collapse, aes(xintercept = min_gen, color = climate, linetype = evolution)) +
    geom_hline(data = collapse, aes(yintercept = collapse_point), alpha = 1, color = "darkgrey") +
  geom_line(aes(color = climate, linetype = evolution)) +
  facet_wrap(~ mpa_size, scales = "free_y", ncol = 1) +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    linetype = "Evolution?",
    color = "Climate"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#440154", "#3b528b", "#21918c", "#5ec962", "#fde725")) 

ggsave(s1, file = paste0("decline_full.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

```{r}
s3 = ggplot(mean_change2, aes(generation, mean_change)) +
  geom_line(aes(color = mpa_size, linetype = evolution)) +
  facet_wrap(~ climate, ncol = 1,scales = "free_y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Rate of Population Change",
    linetype = "Evolution?",
    color = "MPA Size"
  )+
  scale_color_viridis_d() +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(s3, file = paste0("rate.pdf"), path = here::here("04_figs", "supp"), height = 10, width = 15)
```

```{r}
s4 = ggplot(line_df_mpa_full, aes(generation, location_sum)) +
  geom_vline(data = collapse_full, aes(xintercept = min_gen, color = climate, linetype = evolution), alpha = 0.8) +
  geom_hline(data = collapse_full, aes(yintercept = collapse_point), alpha = 1, color = "darkgrey") +
  geom_line(aes(color = climate, linetype = evolution)) +
  facet_wrap(~ mpa_size, scales = 'free', ncol = 1) +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate", fill = "", linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_viridis_d() + scale_fill_viridis_d() +
  guides(fill="none")
  
ggsave(s4, file = paste0("decline_mpa_full.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

```{r}
s5 = ggplot(line_df, aes(generation, log(location_sum))) +
  geom_line(aes(color = climate, linetype = evolution)) +
  facet_wrap(~ mpa_size, ncol = 1) +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate",
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154"))

ggsave(s5, file = paste0("decline_full_sim_log.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

## Climate Rate Figures

```{r}
data_rate <- read_csv(here::here("03_generated_data", "summary_data", "full_sum_climate_rate.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  mutate(mpa_size = case_when(
    mpa_size == "Small" ~ "3 x 3",
    mpa_size == "Medium" ~ "6 x 6",
    mpa_size == "Large" ~ "10 x 10"
  ))
```

```{r}
line_df_mpa_full_rate <- data_rate %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(10) & mpa_size == "10 x 10")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() 

line_df_geno_lat_rate <- data_rate %>%
  filter(lat == 10 | lat == 90 | lat == 50)

line_df_mpa_full_rate = line_df_mpa_full_rate %>% 
  group_by(generation, evolution, mpa_size, climate, climate_rate) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation))

line_df_geno_lat_rate = line_df_geno_lat_rate %>% 
  group_by(generation, evolution, mpa_size, climate, genotype, lat, climate_rate) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_lat_mpa_combo_rate = line_df_geno_lat_rate %>% 
  filter(lat != 50) %>% 
  group_by(generation, climate, genotype, lat, climate_rate) %>% 
  summarize(mpa_mean_freq = mean(freq_avg, na.rm = TRUE)) %>% 
  mutate(location = case_when(
    lat == 10 ~ "Low Latitude", 
    lat == 90 ~ "High Latitude"
  )) %>% 
  mutate(mpa_size = "Non-MPA")

geno_lat_rate = line_df_geno_lat_rate %>% 
  filter(lat == 50) %>% 
  mutate(location = "MPA") %>% 
  mutate(mpa_mean_freq = freq_avg) %>% 
  full_join(line_lat_mpa_combo_rate) %>% 
  mutate(location = as.factor(location)) %>% 
  mutate(mpa_size = as.factor(mpa_size)) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("10 x 10", "6 x 6", "3 x 3", "Non-MPA"))) %>% 
  filter(mpa_size != "Non-MPA")

collapse_full_rate = line_df_mpa_full_rate %>% 
  select(generation, evolution, mpa_size, climate, location_sum, climate_rate) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10") | (location_sum <= (100*2*.05) & mpa_size == "1 x 1")) %>% 
  group_by(evolution, mpa_size, climate, climate_rate) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "1 x 1" ~ 100*2*0.05,
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  ))
```

```{r}
s6 = ggplot(line_df_mpa_full_rate, aes(generation, location_sum)) +
  geom_vline(data = collapse_full_rate, aes(xintercept = min_gen, color = as.factor(climate_rate), linetype = evolution), alpha = 0.8) +
  geom_hline(data = collapse_full_rate, aes(yintercept = collapse_point), alpha = 1, color = "darkgrey") +
  geom_line(aes(color = as.factor(climate_rate), linetype = evolution)) +
  ggh4x::facet_grid2(mpa_size ~ climate, scales = 'free_y', independent = "y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Increase Per Year", linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#5ec962", "#440154")) +
  guides(fill="none")
  
#ggsave(s6, file = paste0("decline_mpa_climate_rate.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

```{r}
s7 = ggplot(geno_lat_rate, aes(generation, mpa_mean_freq)) +
  geom_line(aes(color = as.factor(climate_rate), linetype = mpa_size, alpha = as.factor(climate_rate))) +
  facet_grid(genotype~climate, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Allele Frequency",
    color = "Climate Increase Per Year",
    linetype = "MPA size",
    alpha = ""
  ) +
  theme() +
  scale_color_manual(values = c("#5ec962", "#440154")) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted")) +
  scale_alpha_manual(values = c(1, 0.3), guide = 'none')

s8 = s6 + s7 + plot_annotation(tag_levels = 'A') + plot_layout(guides = "collect")

ggsave(s8, file = paste0("climate_rate.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)

#ggsave(s7, file = paste0("genotype_summary_rate.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

## Fishing Pressure Figures

```{r}
data_fp <- read_csv(here::here("03_generated_data", "summary_data", "full_sum_fishing_pressure.csv")) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(climate = fct_relevel(climate, c("Shocks with Mean Shift", "Mean Shift", "El Nino/La Nina"))) %>% 
  filter(generation <= 150) %>% 
  mutate(mpa_size = case_when(
    mpa_size == "Small" ~ "3 x 3",
    mpa_size == "Medium" ~ "6 x 6",
    mpa_size == "Large" ~ "10 x 10"
  ))
```

```{r}
line_df_fp <- data_fp %>%
  filter(generation > 25) %>%
  group_by(generation, mpa_size, climate, fishing_pressure, evolution) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_mpa_full_fp <- data_fp %>%
  filter(generation > 25) %>%
  filter((lat %in% c(49:51) & mpa_size == "3 x 3") | (lat %in% c(47:52) & mpa_size == "6 x 6") | (lat %in% c(46:55) & mpa_size == "10 x 10") | (lat %in% c(50) & mpa_size == "1 x 1")) %>% 
  filter((lon %in% c(9:11) & mpa_size == "3 x 3") | (lon %in% c(9:14) & mpa_size == "6 x 6") | (lon %in% c(10) & mpa_size == "10 x 10")) %>% 
  select(-genotype, -geno_pop_mean, -geno_pop_sd, -geno_pop_se, -freq) %>%
  distinct() %>% 
  group_by(generation, evolution, mpa_size, climate, fishing_pressure) %>%
  summarise(
    location_sum = sum(pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp)) %>% 
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m)

line_df_geno_lat_fp <- data_fp %>%
  group_by(generation, evolution, mpa_size, climate, genotype, lat, fishing_pressure) %>% 
  summarise(
    location_sum = sum(geno_pop_mean, na.rm = TRUE),
    max_temp = max(max_temp),
    min_temp = min(min_temp),
    freq_avg = mean(freq, na.rm = TRUE)) %>%
  mutate(generation = as.numeric(generation)) %>%
  mutate(min_m = 1 - (1 - exp((-(max_temp - 25)^2) / (4^2)))) %>%
  mutate(min_survival = ifelse(min_m > 0.70, 0.70, min_m)) %>%
  mutate(max_m = 1 - (1 - exp((-(min_temp - 25)^2) / (4^2)))) %>%
  mutate(max_survival = ifelse(max_m > 0.70, 0.70, max_m)) %>%
  select(-max_m, -min_m) %>% 
  filter(evolution == "Yes") %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(max_temp = as.factor(max_temp))

line_df_geno_lat_fp = line_df_geno_lat_fp %>%
  filter(lat == 10 | lat == 90 | lat == 50)

line_lat_mpa_combo_fp = line_df_geno_lat_fp %>% 
  filter(lat != 50) %>% 
  group_by(generation, climate, genotype, lat, fishing_pressure, evolution) %>% 
  summarize(mpa_mean_freq = mean(freq_avg, na.rm = TRUE)) %>% 
  mutate(location = case_when(
    lat == 10 ~ "Low Latitude", 
    lat == 90 ~ "High Latitude"
  )) %>% 
  mutate(mpa_size = "Non-MPA") 

geno_lat_fp = line_df_geno_lat_fp %>% 
  filter(lat == 50) %>% 
  mutate(location = "MPA") %>% 
  mutate(mpa_mean_freq = freq_avg) %>% 
  full_join(line_lat_mpa_combo_fp) %>% 
  mutate(location = as.factor(location)) %>% 
  mutate(mpa_size = as.factor(mpa_size)) %>% 
  mutate(mpa_size = fct_relevel(mpa_size, c("10 x 10", "6 x 6", "3 x 3", "Non-MPA"))) %>% 
  filter(mpa_size != "Non-MPA")

collapse_fp = line_df_fp %>% 
  select(generation, mpa_size, climate, location_sum, fishing_pressure, evolution) %>% 
  filter(generation > 30) %>% 
  filter(location_sum <= 100*2*.05*100*20) %>% 
  group_by(mpa_size, climate, fishing_pressure, evolution) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = 100*2*.05*100*20)

collapse_full_fp = line_df_mpa_full_fp %>% 
  select(generation, evolution, mpa_size, climate, location_sum, fishing_pressure) %>% 
  filter(generation > 30) %>% 
  filter((location_sum <= (100*2*.05*3*3) & mpa_size == "3 x 3") | (location_sum <= (100*2*.05*6*6) & mpa_size == "6 x 6") | (location_sum <= (100*2*.05*10*10) & mpa_size == "10 x 10") | (location_sum <= (100*2*.05) & mpa_size == "1 x 1")) %>% 
  group_by(evolution, mpa_size, climate, fishing_pressure) %>%
  summarize(min_gen = min(generation)) %>% 
  mutate(collapse_point = case_when(
    mpa_size == "1 x 1" ~ 100*2*.05,
    mpa_size == "3 x 3" ~ 100*2*.05*3*3,
    mpa_size == "6 x 6" ~ 100*2*.05*6*6,
    mpa_size == "10 x 10" ~ 100*2*.05*10*10
  ))
```


```{r}
s9 = ggplot(geno_lat_fp, aes(generation, mpa_mean_freq)) +
  geom_line(aes(color = as.factor(fishing_pressure), linetype = mpa_size, alpha = as.factor(fishing_pressure))) +
  facet_grid(genotype~climate, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Allele Frequency",
    color = "Fishing Pressure",
    linetype = "MPA size",
    alpha = ""
  ) +
  theme() +
  scale_color_manual(values = c("#5ec962", "#440154")) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted")) +
  scale_alpha_manual(values = c(1, 0.3), guide = 'none')

#ggsave(s9, file = paste0("genotype_summary_fishing_pressure.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

```{r}
s10 = ggplot(line_df_mpa_full_fp, aes(generation, location_sum)) +
  geom_vline(data = collapse_full_fp, aes(xintercept = min_gen, color = as.factor(fishing_pressure), linetype = evolution), alpha = 0.8) +
  geom_hline(data = collapse_full_fp, aes(yintercept = collapse_point), alpha = 1, color = "darkgrey") +
  geom_line(aes(color = as.factor(fishing_pressure), linetype = evolution)) +
  ggh4x::facet_grid2(mpa_size ~ climate, scales = 'free_y', independent = "y") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Fishing Pressure", linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#5ec962", "#440154")) 
  
s11 = s10 + s9 + plot_annotation(tag_levels = 'A') + plot_layout(guides = "collect")

ggsave(s11, file = paste0("fishing_pressure.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
  
#ggsave(s10, file = paste0("decline_mpa_fishing_pressure.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```

## Climate Figures

```{r}
years <- 175
NS.patches <- 100
EW.patches <- 20
opt.temp <- 25

calc_temp_mortality <- function(SST, opt.temp, temp.range, s) {
  nat.m <- array(0, c(nrow(SST), ncol(SST)))
  m <- 1 - exp((-(SST[, ] - opt.temp)^2) / (temp.range^2)) # temperature based mortality function from Walsworth et al.
  m <- 1 - m
  nat.m <- ifelse(m > s, s, m)
  return(nat.m)
}

### UNCOMMENT FOR CONSTANT MEAN SHIFT SST
SST.patches.mean <- array(opt.temp, c(NS.patches, EW.patches, years))
start_SST <- (opt.temp) + NS.patches * 0.02

for (i in 1:25) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.mean[lat, , i] <- SST
    SST <- SST - 0.02
  }
}

for (i in 26:years) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.mean[lat, , i] <- SST
    SST <- SST - 0.02
  }
  start_SST <- start_SST + 0.033
}

### UNCOMMENT FOR ENSO VARIABLE MEAN SST
SST.patches.enso <- array(opt.temp, c(NS.patches, EW.patches, years))
start_SST <- (opt.temp) + NS.patches * 0.02

for (i in 1:25) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.enso[lat, , i] <- SST
    SST <- SST - 0.02
  }
}

t <- seq(1, years - 25, 1)
b <- array(0, 25)
change <- 0.5 * sin(t) + 0.033
enso.value <- c(b, change)

for (i in 26:years) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.enso[lat, , i] <- SST
    SST <- SST - 0.02
  }
  start_SST <- start_SST + enso.value[i]
}

### UNCOMMENT FOR SHOCK SST CHANGES
SST.patches.shock <- array(opt.temp, c(NS.patches, EW.patches, years))
start_SST <- (opt.temp) + NS.patches * 0.02

for (i in 1:25) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.shock[lat, , i] <- SST
    SST <- SST - 0.02
  }
}

for (i in 26:years) {
  SST <- start_SST
  heat_prob <- runif(1, 0, 1)
  if ((i < 75 & heat_prob < 0.1) | (i >= 75 & heat_prob < 0.35)) {
    intensity <- runif(1, 1, 4)
    SST <- start_SST + intensity
  } else {
    SST <- start_SST
  }
  for (lat in 1:NS.patches) {
    SST.patches.shock[lat, , i] <- SST
    SST <- SST - 0.02
  }
}

### MEAN SHOCK
SST.patches.mean.shock <- array(opt.temp, c(NS.patches, EW.patches, years))
start_SST <- (opt.temp) + NS.patches * 0.02

for (i in 1:25) {
  SST <- start_SST
  for (lat in 1:NS.patches) {
    SST.patches.mean.shock[lat, , i] <- SST
    SST <- SST - 0.02
  }
}

for (i in 26:years) {
  heat_prob <- runif(1, 0, 1)
  if ((i < 75 & heat_prob < 0.1) | (i >= 75 & heat_prob < 0.35)) {
    intensity <- runif(1, 1, 4)
    SST <- start_SST + intensity
  } else {
    SST <- start_SST
  }
  for (lat in 1:NS.patches) {
    SST.patches.mean.shock[lat, , i] <- SST
    SST <- SST - 0.02
  }
  start_SST <- start_SST + 0.033
}

output_df_mean <- data.frame() # create dataframe to hold results
output_df_enso <- data.frame()
output_df_shock <- data.frame()
output_df_mean_shock <- data.frame()


# Mean --------------------------------------------------------------------

for (b in 1:years) {
  SSTdf_mean <- SST.patches.mean[, , b] %>%
    as.data.frame()

  SSTdf_mean$lat <- c(1:NS.patches)
  SSTdf_mean$year <- paste0(b)

  output_df_mean <- bind_rows(output_df_mean, SSTdf_mean)
}

SSTdf_mean <- output_df_mean %>%
  pivot_longer(V1:V20,
    names_to = "lon",
    values_to = "sst"
  ) %>%
  mutate(lon = case_when(
    lon == "V1" ~ 1,
    lon == "V2" ~ 2,
    lon == "V3" ~ 3,
    lon == "V4" ~ 4,
    lon == "V5" ~ 5,
    lon == "V6" ~ 6,
    lon == "V7" ~ 7,
    lon == "V8" ~ 8,
    lon == "V9" ~ 9,
    lon == "V10" ~ 10,
    lon == "V11" ~ 11,
    lon == "V12" ~ 12,
    lon == "V13" ~ 13,
    lon == "V14" ~ 14,
    lon == "V15" ~ 15,
    lon == "V16" ~ 16,
    lon == "V17" ~ 17,
    lon == "V18" ~ 18,
    lon == "V19" ~ 19,
    lon == "V20" ~ 20
  )) %>%
  mutate(year = as.numeric(year))

for (b in 1:years) {
  SSTdf_enso <- SST.patches.enso[, , b] %>%
    as.data.frame()
  
  SSTdf_enso$lat <- c(1:NS.patches)
  SSTdf_enso$year <- paste0(b)
  
  output_df_enso <- bind_rows(output_df_enso, SSTdf_enso)
}

SSTdf_enso <- output_df_enso %>%
  pivot_longer(V1:V20,
               names_to = "lon",
               values_to = "sst"
  ) %>%
  mutate(lon = case_when(
    lon == "V1" ~ 1,
    lon == "V2" ~ 2,
    lon == "V3" ~ 3,
    lon == "V4" ~ 4,
    lon == "V5" ~ 5,
    lon == "V6" ~ 6,
    lon == "V7" ~ 7,
    lon == "V8" ~ 8,
    lon == "V9" ~ 9,
    lon == "V10" ~ 10,
    lon == "V11" ~ 11,
    lon == "V12" ~ 12,
    lon == "V13" ~ 13,
    lon == "V14" ~ 14,
    lon == "V15" ~ 15,
    lon == "V16" ~ 16,
    lon == "V17" ~ 17,
    lon == "V18" ~ 18,
    lon == "V19" ~ 19,
    lon == "V20" ~ 20
  )) %>%
  mutate(year = as.numeric(year))

for (b in 1:years) {
  SSTdf_shock <- SST.patches.shock[, , b] %>%
    as.data.frame()
  
  SSTdf_shock$lat <- c(1:NS.patches)
  SSTdf_shock$year <- paste0(b)
  
  output_df_shock <- bind_rows(output_df_shock, SSTdf_shock)
}

SSTdf_shock <- output_df_shock %>%
  pivot_longer(V1:V20,
               names_to = "lon",
               values_to = "sst"
  ) %>%
  mutate(lon = case_when(
    lon == "V1" ~ 1,
    lon == "V2" ~ 2,
    lon == "V3" ~ 3,
    lon == "V4" ~ 4,
    lon == "V5" ~ 5,
    lon == "V6" ~ 6,
    lon == "V7" ~ 7,
    lon == "V8" ~ 8,
    lon == "V9" ~ 9,
    lon == "V10" ~ 10,
    lon == "V11" ~ 11,
    lon == "V12" ~ 12,
    lon == "V13" ~ 13,
    lon == "V14" ~ 14,
    lon == "V15" ~ 15,
    lon == "V16" ~ 16,
    lon == "V17" ~ 17,
    lon == "V18" ~ 18,
    lon == "V19" ~ 19,
    lon == "V20" ~ 20
  )) %>%
  mutate(year = as.numeric(year))

for (b in 1:years) {
  SSTdf_mean_shock <- SST.patches.mean.shock[, , b] %>%
    as.data.frame()
  
  SSTdf_mean_shock$lat <- c(1:NS.patches)
  SSTdf_mean_shock$year <- paste0(b)
  
  output_df_mean_shock <- bind_rows(output_df_mean_shock, SSTdf_mean_shock)
}

SSTdf_mean_shock <- output_df_mean_shock %>%
  pivot_longer(V1:V20,
               names_to = "lon",
               values_to = "sst"
  ) %>%
  mutate(lon = case_when(
    lon == "V1" ~ 1,
    lon == "V2" ~ 2,
    lon == "V3" ~ 3,
    lon == "V4" ~ 4,
    lon == "V5" ~ 5,
    lon == "V6" ~ 6,
    lon == "V7" ~ 7,
    lon == "V8" ~ 8,
    lon == "V9" ~ 9,
    lon == "V10" ~ 10,
    lon == "V11" ~ 11,
    lon == "V12" ~ 12,
    lon == "V13" ~ 13,
    lon == "V14" ~ 14,
    lon == "V15" ~ 15,
    lon == "V16" ~ 16,
    lon == "V17" ~ 17,
    lon == "V18" ~ 18,
    lon == "V19" ~ 19,
    lon == "V20" ~ 20
  )) %>%
  mutate(year = as.numeric(year))

SSTdf_mean <- SSTdf_mean %>%
  mutate(mortality = 1 - (1 - exp((-(sst - 25)^2) / (4^2)))) %>%
  mutate(survival = ifelse(mortality > 0.7, 0.7, mortality)) %>% 
  filter(lat %in% c(1,50,100)) %>% 
  filter(lon == 10) %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(lat = case_when(
    lat == 1 ~ "Lowest Latitude",
    lat == 100 ~ "Highest Latitude",
    lat == 50 ~ "Within MPA"
  )) %>% filter(lat == "Within MPA") %>% 
  mutate(climate = "Mean Shift")

SSTdf_enso <- SSTdf_enso %>%
  mutate(mortality = 1 - (1 - exp((-(sst - 25)^2) / (4^2)))) %>%
  mutate(survival = ifelse(mortality > 0.7, 0.7, mortality)) %>% 
  filter(lat %in% c(1,50,100)) %>% 
  filter(lon == 10) %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(lat = case_when(
    lat == 1 ~ "Lowest Latitude",
    lat == 100 ~ "Highest Latitude",
    lat == 50 ~ "Within MPA"
  )) %>% filter(lat == "Within MPA") %>% 
  mutate(climate = "El Nino/ La Nina")

SSTdf_shock <- SSTdf_shock %>%
  mutate(mortality = 1 - (1 - exp((-(sst - 25)^2) / (4^2)))) %>%
  mutate(survival = ifelse(mortality > 0.7, 0.7, mortality)) %>% 
  filter(lat %in% c(1,50,100)) %>% 
  filter(lon == 10) %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(lat = case_when(
    lat == 1 ~ "Lowest Latitude",
    lat == 100 ~ "Highest Latitude",
    lat == 50 ~ "Within MPA"
  )) %>% filter(lat == "Within MPA") %>% 
  mutate(climate = "Shocks")

SSTdf_mean_shock <- SSTdf_mean_shock %>%
  mutate(mortality = 1 - (1 - exp((-(sst - 25)^2) / (4^2)))) %>%
  mutate(survival = ifelse(mortality > 0.7, 0.7, mortality)) %>% 
  filter(lat %in% c(1,50,100)) %>% 
  filter(lon == 10) %>% 
  mutate(lat = as.factor(lat)) %>% 
  mutate(lat = case_when(
    lat == 1 ~ "Lowest Latitude",
    lat == 100 ~ "Highest Latitude",
    lat == 50 ~ "Within MPA"
  )) %>% filter(lat == "Within MPA") %>% 
  mutate(climate = "Shocks with Mean Shift")

SSTdf = list(SSTdf_enso, SSTdf_mean, SSTdf_mean_shock, SSTdf_shock) %>% 
  reduce(full_join)

temp = ggplot(SSTdf) +
  geom_line(aes(year, sst), color = "blue") +
  geom_hline(aes(yintercept = 25), alpha = 0.5, linetype = "dashed") + 
  geom_hline(aes(yintercept = 27), alpha = 0.5, linetype = "dashed", color = "red") + 
  facet_wrap(~ climate) +
  labs(x = "Year", y = "SST") +
  theme_bw() +
  scale_color_viridis_d() +
  theme(
    panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold"),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    strip.background = element_rect(fill = "white")
  )

# temp = ggplot(SSTdf_enso) +
#   geom_line(aes(year, sst), color = "blue", linewidth = .2) +
#   labs(x = "Year", y = "SST") +
#   theme_bw(base_size= 5) +
#   scale_color_viridis_d() +
#   theme(
#     panel.grid = element_blank(),
#     panel.grid.minor = element_blank(),
#     strip.text = element_text(face = "bold"),
#     axis.ticks = element_blank(),
#     axis.text = element_blank(),
#     strip.background = element_rect(fill = "white")
#   ) + 
#   ylim(c(26,33))


ggsave(temp, file = paste0("temp.pdf"), path = here("04_figs", "climate"), height = 10, width = 10)
```

```{r}
# Model Parameter set up --------------------------------------------------

SST <- seq(10, 40) # sea surface temperatures to model

opt.temp <- 25 # optimal temperature ranges

temp.range <- 4 # thermal performance range, w


# Mortality Function ------------------------------------------------------

calc_mortality <- function(SST, opt.temp, temp.range) {
  nat.m <- 1 - exp((-(SST - opt.temp)^2) / (temp.range^2)) # temperature based mortality function from Walsworth et al.
  return(1 - nat.m)
}


# Simulate Mortality Rates Function -----------------------------------------------

simulate_mortality <- function(SST, opt.temp, temp.range) {
  results <- matrix(NaN, nrow = length(SST), ncol = 1) # empty matrix to hold results


  for (i in 1:length(SST)) {
    for (j in 1:length(opt.temp)) {
      mort <- calc_mortality(SST[i], opt.temp, temp.range)
      results[i][j] <- mort
    }
  }

  results_plot <- as.data.frame(results) %>%
    rename(survival = V1) %>%
    mutate(survival.prop = case_when(
      survival > .7 ~ .7,
      survival < .7 ~ survival
    ))

  results_plot$SST <- SST
  results_plot$opt.temp <- opt.temp
  results_plot$range <- temp.range

  return(results_plot)
}



# Simulate multiple optimal temperatures ----------------------------------

simulation_results <- data.frame()

for (k in 1:length(opt.temp)) {
  sub_result <- simulate_mortality(SST, opt.temp[k], temp.range)
  simulation_results <- bind_rows(sub_result, simulation_results)
}

simulation_results <- simulation_results %>%
  mutate(opt.temp = as.factor(opt.temp))

mort_curve = ggplot(simulation_results, aes(SST, survival.prop)) +
  geom_line(linewidth = 1) +
  geom_vline(aes(xintercept = 25), linetype = "dashed", alpha = 0.5, color = "blue") +
  geom_vline(aes(xintercept = 27), linetype = "dotted", color = "blue") +
  geom_vline(aes(xintercept = 23), linetype = "dotted", color = "blue") +
  geom_vline(aes(xintercept = 34.19259), linetype = "longdash", alpha = 0.3, color = "red") +
  geom_vline(aes(xintercept = 31.84384), linetype = "longdash", alpha = 0.3, color = "red") +
  geom_vline(aes(xintercept = 30.93700), linetype = "longdash", alpha = 0.3, color = "red") +
  geom_vline(aes(xintercept = 29.66092), linetype = "longdash", alpha = 0.3, color = "red") +
  theme_bw()+
  labs(
    x = "Sea Surface Temperature",
    y = "Survival Probability"
  ) +
  theme(panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 25,  hjust=1)) +
  scale_x_continuous(breaks = c(23, 25, 27, 29.66092, 30.93700, 31.84384, 34.19259), labels = c("Thermal Min", "Thermal Optimum", "Thermal Max", "Shocks Max", "Mean Shift Max", "El Nino/ La Nina Max", "Shocks with Mean Shift Max"))

ggsave(mort_curve, file = paste0("mort_curve.pdf"), path = here("04_figs", "climate"), height = 10, width = 10)
```


# Presentation Figures

```{r}
mpa_medium_null = mpa_medium %>% 
  filter(climate %in% c("Null")) %>% 
  mutate(climate = case_when(
    climate == "Null" ~ "No Climate Change"
  ))

mpa_medium_mean = mpa_medium %>% 
  filter(climate %in% c("Mean Shift")) %>% 
  mutate(climate = case_when(
    climate == "Mean Shift" ~ "Mean Change Per Year"
  )) 
  

p1 = ggplot(mpa_medium_null, aes(generation, location_sum)) +
  geom_line(aes(color = climate, linetype = evolution), linewidth = 2) +
  theme_bw(base_size = 20) +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Scenario", 
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#5ec962")) +
  scale_linetype_manual(values = c("solid", "dashed"))
  
ggsave(p1, file = paste0("decline_mpa_pres_null.pdf"), path = here::here("04_figs", "presentation"), height = 10, width = 18)

p2 = ggplot() +
  geom_line(data = mpa_medium_null, aes(generation, location_sum, linetype = evolution, color = climate), linewidth = 2) +
  geom_line(data = mpa_medium_mean, aes(generation, location_sum, linetype = evolution, color = climate), linewidth = 3) +
  theme_bw(base_size = 20) +
  labs(
    x = "Year",
    y = "Population Density",
    color = "Climate Scenario", 
    linetype = "Evolution?"
  ) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(values = c("#440154", "#5ec962")) +
  scale_linetype_manual(values = c("solid", "dashed"))
  
ggsave(p2, file = paste0("decline_mpa_pres_mean.pdf"), path = here::here("04_figs", "presentation"), height = 10, width = 18)
```



# Old

```{r}
# geno_lat_pres = geno_lat %>% 
#   filter(location == "MPA") %>% 
#   filter(climate %in% c("Null", "Mean Shift")) %>% 
#   mutate(climate = case_when(
#     climate == "Null" ~ "No Climate Change",
#     climate == "Mean Shift" ~ "Mean Change Per Year"
#   )) %>% 
#   filter(mpa_size == "6 x 6")
# 
# p2 = ggplot(geno_lat_pres, aes(generation, mpa_mean_freq)) +
#   geom_line(aes(color = mpa_size), linewidth = 2) +
#   facet_grid(genotype~climate, scales = "free_y") +
#   theme_bw(base_size = 20) +
#   labs(
#     x = "Year",
#     y = "Allele Frequency",
#     color = "MPA Size"
#   ) +
#   theme() +
#   scale_color_viridis_d() +
#   theme(panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold"),
#         strip.background = element_rect(fill = "white"),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank())
# 
# ggsave(p2, file = paste0("genotype_summary_pres.pdf"), path = here::here("04_figs", "presentation"), height = 8, width = 15)
```

```{r}
# p2 = ggplot(line_df_geno, aes(generation, freq_avg)) +
#   geom_line(aes(color = climate)) +
#   facet_wrap(genotype~ mpa_size, scales = 'free', ncol = 3) +
#   theme_bw() +
#   labs(
#     x = "Year",
#     y = "Allele Frequency",
#     color = "Fishing Pressure"
#   ) +
#   theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
#   scale_color_viridis_d() +
#   theme(panel.grid.minor = element_blank())
# 
# ggsave(p2, file = paste0("sum_geno.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

```{r}
# line_df_lat = line_df_lat %>% 
#   filter(lat == 10 | lat == 90 | lat == 50)
# shock_df_lat = line_df_lat %>% 
#   filter(climate == "Shock") %>% 
#   filter(lat == 10 | lat == 90 | lat == 50)
# mean_shock_df_lat = line_df_lat %>% 
#   filter(climate == "Mean Shock") %>% 
#   filter(lat == 10 | lat == 90 | lat == 50)
# mean_df_lat = line_df_lat %>% 
#   filter(climate == "Mean") %>% 
#   filter(lat == 10 | lat == 90 | lat == 50)
# null_df_lat = line_df_lat %>% 
#   filter(climate == "Null") %>% 
#   filter(lat == 10 | lat == 90 | lat == 50)

# p3 = ggplot(line_df_lat, aes(generation, location_sum)) +
#   geom_line(aes(group = location, color = mpa)) +
#   ggh4x::facet_grid2(climate ~ mpa_size, scales = 'free_y', independent = "y") +
#   theme_bw() +
#   labs(
#     x = "Year",
#     y = "Population Density",
#     color = ""
#   ) +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#   theme(panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold"),
#         strip.background = element_rect(fill = "white")) +
#   scale_color_viridis_d()
# 
# ggsave(p3, file = paste0("mpa_benefit_summary.pdf"), path = here::here("04_figs"), height = 10, width = 15)
```

```{r}
# p4 = ggplot(line_df_geno_lat, aes(generation, freq_avg)) +
#   geom_line(aes(color = lat, linetype = climate)) +
#   facet_wrap(genotype~mpa_size, scales = 'free') +
#   theme_bw() +
#   labs(
#     x = "Year",
#     y = "Allele Frequency",
#     color = "Latitude",
#     linetype = "Climate"
#   ) +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#   theme(panel.grid.minor = element_blank()) +
#   scale_color_viridis_d()
# 
# ggsave(p4, file = paste0("sum_lat_geno_clim.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

```{r}
# p6 = ggplot(mean_change, aes(lat, mean_change)) +
#   geom_vline(data = mpa_boundaries, aes(xintercept = r_bound), alpha = 0.3, linetype = "dashed") +
#   geom_vline(data = mpa_boundaries, aes(xintercept = l_bound), alpha = 0.3, linetype = "dashed") +
#   geom_line(aes(color = evolution)) +
#   theme_bw() +
#   ggh4x::facet_grid2(mpa_size ~ climate) + 
#   theme(panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold"),
#         strip.background = element_rect(fill = "white"),
#         # axis.text.y = element_blank(),
#         # axis.ticks.y = element_blank(),
#         axis.text.x = element_text(angle = 60, hjust=1)) +
#   scale_color_viridis_d() +
#   labs(
#     x = "Latitude",
#     y = "Mean Rate of Change",
#     color = "Evolution?"
#   ) +
#   coord_flip()
# 
# ggsave(p6, file = paste0("rate_lat.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

```{r}
# p14 = ggplot(line_df_fp, aes(generation, location_sum)) +
#   geom_vline(data = collapse_fp, aes(xintercept = min_gen, color = as.factor(fishing_pressure), linetype = evolution), alpha = 0.8) +
#   geom_hline(data = collapse_fp, aes(yintercept = collapse_point), alpha = 1, color = "darkgrey") +
#   geom_line(aes(color = as.factor(fishing_pressure), linetype = evolution)) +
#   ggh4x::facet_grid2(mpa_size ~ climate, scales = 'free_y', independent = "y") +
#   theme_bw() +
#   labs(
#     x = "Year",
#     y = "Population Density",
#     color = "Fishing Pressure", linetype = "Evolution?"
#   ) +
#   theme(panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold"),
#         strip.background = element_rect(fill = "white"),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank()) +
#   scale_color_manual(values = c("#5ec962", "#440154")) 
#   
# ggsave(p14, file = paste0("decline_sim_fishing_pressure.pdf"), path = here::here("04_figs"), height = 8, width = 15)
```

```{r}
# s2 = ggplot(line_df_mpa, aes(generation, pop_mean)) +
#   geom_line(aes(color = climate, linetype = evolution)) +
#   geom_ribbon(aes(ymin = pop_mean - pop_se, ymax = pop_mean + pop_se, fill = climate, linetype = evolution), alpha = .2) +
#   facet_wrap(~ mpa_size, scales = 'free', ncol = 1) +
#   theme_bw() +
#   labs(
#     x = "Year",
#     y = "Population Density",
#     color = "Climate", fill = "", linetype = "Evolution?"
#   ) +
#   theme(panel.grid.minor = element_blank(),
#         strip.text = element_text(face = "bold"),
#         strip.background = element_rect(fill = "white"),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank()) +
#   scale_color_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154")) +
#   scale_fill_manual(values = c("#21918c", "#5ec962", "#fde725", "#3b528b", "#440154")) +
#   guides(fill="none")
#   
# ggsave(s2, file = paste0("decline_mpa.pdf"), path = here::here("04_figs", "supp"), height = 8, width = 15)
```