---
title: ''
author: "Allie Caughman"
date: '2022-07-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(patchwork)
```

### Load in data

```{r}
test_null8 = read_csv(here::here("output", "test_null8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "null8")

test_mean8 = read_csv(here::here("output", "test_mean8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "mean8")

test_enso8 = read_csv(here::here("output", "test_enso8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "enso8")

test_shock8 = read_csv(here::here("output", "test_shock8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "shock8") 

test_null_noevo = read_csv(here::here("output", "test_null_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "null_noevo")

test_mean_noevo = read_csv(here::here("output", "test_mean_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "mean_noevo")

test_null5 = read_csv(here::here("output", "test_null5.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "null5")

test_mean5 = read_csv(here::here("output", "test_mean5.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "mean5")

test_enso5 = read_csv(here::here("output", "test_enso5.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "enso5") 

test_shock5 = read_csv(here::here("output", "test_shock5.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "shock5") 

data1 = full_join(test_mean8, test_null8)
data2 = full_join(data1, test_enso8)
data3 = full_join(data2, test_shock8)
data4 = full_join(data3, test_enso5)
data5 = full_join(data4, test_shock5)
data6 = full_join(data5, test_mean5)
data7 = full_join(data6, test_null5)
data8 = full_join(data7, test_mean_noevo)
data = full_join(data8, test_null_noevo) %>% 
  mutate(location = str_c(lat,lon,generation))

data_sum = data %>% 
  group_by(generation, type) %>% 
  summarize(mean_pop = mean(geno_pop_sum))
```

### paired t-test or repeated measures ANOVA 

```{r}
null8 = data %>% 
  filter(type == "null8") %>% 
  pull(geno_pop_sum)
null_noevo = data %>% 
  filter(type == "null_noevo") %>% 
  pull(geno_pop_sum)

test_noevo = t.test(null8, null_noevo, paired = TRUE, alternative = "two.sided")
```

```{r}
##ERRORED

data8 = data %>% 
  filter(type %in% c("null8", "mean8", "enso8", "shock8", "null_noevo", "mean_noevo"))

data5 = data %>% 
  filter(type %in% c("null5", "mean5", "enso5", "shock5"))

# test_climate8 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data8)
# 
# test_climate5 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data5)

sum_climate8 = data8 %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))

sum_climate5 = data5 %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation))
```


### MPA only squares

```{r}
data_f = data %>% 
  filter(lon %in% c(9, 10, 11)) %>% 
  filter(lat %in% c(10, 11, 12))

data_f_sum = data_f %>% 
  group_by(generation, type) %>% 
  summarize(mean_pop = mean(geno_pop_sum))
```

```{r}
#don't think this is necessary
null8_f = data_f %>% 
  filter(type == "null8") %>% 
  pull(geno_pop_sum)
null_noevo_f = data_f %>% 
  filter(type == "null_noevo") %>% 
  pull(geno_pop_sum)

test_mpa_noevo = t.test(null8_f, null_noevo_f, paired = TRUE, alternative = "two.sided")
```

```{r}
data8_f = data_f %>% 
  filter(type %in% c("null8", "mean8", "enso8", "shock8", "null_noevo", "mean_noevo"))

data5_f = data_f %>% 
  filter(type %in% c("null5", "mean5", "enso5", "shock5"))

test_climate8 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data8_f)

pair_climate8 = pairwise.t.test(
  x = data8_f$geno_pop_sum,
  g = data8_f$type,
  p.adjust.method = 'bonferroni')

test_climate5 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data5_f)

pair_climate5 = pairwise.t.test(
  x = data5_f$geno_pop_sum,
  g = data5_f$type,
  p.adjust.method = 'bonferroni')

sum_climate8_f = data8_f %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))

sum_climate5_f = data5_f %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation))
```

```{r}
p8 = ggplot(sum_climate8_f, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")

p5 = ggplot(sum_climate5_f, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")

plot = p8 / p5 + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

ggsave(p8, file=paste0("test_mpa.pdf"), path = here::here("figs", "test"), height = 8, width = 8)

p_f = ggplot(sum_climate8_f, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  facet_wrap(~cat, scales = "free_y", ncol = 1) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")
```

```{r}
p = ggplot(sum_climate8, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  facet_wrap(~cat, scales = "free_y", ncol = 1) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")

p

ggsave(p, file=paste0("test.pdf"), path = here::here("figs", "test"), height = 11, width = 8)
```

