---
title: ''
author: "Allie Caughman"
date: '2022-07-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(patchwork)
library(effsize)
library(effectsize)
```

### Load in data

```{r}
test_null8 = read_csv(here::here("output", "test_null8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "null8")

test_mean8 = read_csv(here::here("output", "test_mean8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "mean8")

test_enso8 = read_csv(here::here("output", "test_enso8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "enso8")

test_shock8 = read_csv(here::here("output", "test_shock8.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "shock8") 

test_null_noevo = read_csv(here::here("output", "test_null_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "null_noevo")

test_mean_noevo = read_csv(here::here("output", "test_mean_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "mean_noevo")

test_enso_noevo = read_csv(here::here("output", "test_enso_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "enso_noevo")

test_shock_noevo = read_csv(here::here("output", "test_shock_noevo.csv")) %>% 
  filter(generation > 25) %>% 
  group_by(lat, lon, generation) %>% 
  summarise(geno_pop_sum = sum(pop)) %>% 
  mutate(type = "shock_noevo")

data1 = full_join(test_mean8, test_null8)
data2 = full_join(data1, test_enso8)
data3 = full_join(data2, test_shock8)
data8 = full_join(data3, test_mean_noevo)
data9 = full_join(data8, test_enso_noevo)
data10 = full_join(data9, test_shock_noevo)
data = full_join(data10, test_null_noevo) %>%
  mutate(location = str_c(lat,lon,generation))

rm(data1,data2,data3,data8,data9,data10,test_shock_noevo,test_enso_noevo,test_mean_noevo,test_null_noevo,test_null8,test_mean8,test_enso8,test_shock8)

```

### paired t-test or repeated measures ANOVA 

```{r}
##ERRORED

# test_climate8 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data)
# 

sum_climate8 = data %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))

```

### MPA only squares

```{r}
data_f = data %>% 
  filter(lon %in% c(9, 10, 11)) %>% 
  filter(lat %in% c(10, 11, 12))
```

compare MPAs in climates

```{r}
test_climate8 = aov(formula = geno_pop_sum ~ type + Error(location/type), data = data_f)

eta_squared(test_climate8, partial = TRUE)
eta_squared(test_climate8, partial = FALSE)

pairwise.t.test(
  x = data_evo$geno_pop_sum,
  g = data_evo$type,
  p.adjust.method = 'bonferroni')
```

```{r}
sum_climate8_f = data_f %>% 
  group_by(type, generation) %>% 
  summarise(pop_mean = mean(geno_pop_sum)) %>%
  mutate(generation = as.numeric(generation)) %>% 
  mutate(cat = case_when(
    str_detect(type, "null") ~ "null",
    str_detect(type, "mean") ~ "mean",
    str_detect(type, "enso") ~ "enso",
    str_detect(type, "shock") ~ "shock"
  ))
```

```{r}
p8 = ggplot(sum_climate8_f, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")

p8

#ggsave(p8, file=paste0("test_mpa.pdf"), path = here::here("figs", "test"), height = 8, width = 8)

p_f = ggplot(sum_climate8_f, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  facet_wrap(~cat, scales = "free_y", ncol = 1) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")
p_f
```

```{r}
p = ggplot(sum_climate8, aes(generation, pop_mean)) +
  geom_line(aes(color = type)) +
  facet_wrap(~cat, scales = "free_y", ncol = 1) +
  theme_bw() +
  labs(x = "Year", 
       y = "Population Density", 
       color = "")

p

#ggsave(p, file=paste0("test.pdf"), path = here::here("figs", "test"), height = 11, width = 8)
```

